
name: Build and Test AES
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build the AES library
        run: make

      - name: Run the tests
        run: |
          python -c "import unittest, test_rijndael; unittest.main(module=test_rijndael)"